runtime: php
env: flex

runtime_config:
  document_root: public
  #enable_stackdriver_integration: true
  whitelist_functions: proc_open,exec,passthru,proc_open,proc_close,shell_exec,show_source,symlink,system

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env
  - composer.lock

env_variables:
  # Put production environment variables here.
  #LOG_CHANNEL: stackdriver
  APP_LOG: errorlog
  APP_KEY: base64:ESHhXpyAI12IEbrkQ1Do6m0lyO1opnQQO6+SnBok0xE=
  STORAGE_DIR: /storage
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  DB_HOST: 127.0.0.1
  DB_DATABASE: irr
  DB_USERNAME: espetorx
  DB_PASSWORD: espetorxirr
  DB_SOCKET: /cloudsql/setapp-testes:us-central1:irr
  FILESYSTEM_DRIVER: gcs
  GOOGLE_CLOUD_PROJECT_ID: setapp-testes
  GOOGLE_CLOUD_STORAGE_BUCKET: setapp-testes:us-central1:irr.appspot.com
beta_settings:
  cloud_sql_instances: setapp-testes:us-central1:irr